apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  ports:
    - name: "2000"
      port: 2000
      targetPort: 2000
  selector:
    io.kompose.service: webapp
